// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACw00G1Arwz4t6W3Q0HG50IqZp8AJheYI',
    appId: '1:392415090968:android:3b728d5dd718d889b5a66d',
    messagingSenderId: '392415090968',
    projectId: 'tech-218a6',
    databaseURL: 'https://tech-218a6-default-rtdb.firebaseio.com',
    storageBucket: 'tech-218a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnud8zHCRbCFTVtLcm5LasQVjtyz3MbXk',
    appId: '1:392415090968:ios:80f227fff604c033b5a66d',
    messagingSenderId: '392415090968',
    projectId: 'tech-218a6',
    databaseURL: 'https://tech-218a6-default-rtdb.firebaseio.com',
    storageBucket: 'tech-218a6.firebasestorage.app',
    iosBundleId: 'com.example.techlapAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9cAuyJywcHS04q9yNm1uRXcbHiXkc4Zg',
    appId: '1:392415090968:web:a1f3bfc496d6c767b5a66d',
    messagingSenderId: '392415090968',
    projectId: 'tech-218a6',
    authDomain: 'tech-218a6.firebaseapp.com',
    databaseURL: 'https://tech-218a6-default-rtdb.firebaseio.com',
    storageBucket: 'tech-218a6.firebasestorage.app',
  );
}
